name: ec2-deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        run: |
              echo "${{ secrets.DEPLOY_KEY }}" > webserver.pem
              chmod 400 webserver.pem
              ssh -i "webserver.pem" ubuntu@ec2-3-80-251-172.compute-1.amazonaws.com 'date >> date.txt'
