name: ec2-deploy-testrepo
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-80-251-172.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            docker run hello-world
            echo docker-installed >> docker-installed-ek-wari-fer.txt
