...
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      #- name: Install dependencies
      #  run: |
          # Add commands to install any dependencies your project needs

      - name: Deploy to EC2
        run: |
              echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
              chmod 600 deploy_key.pem
              ssh -i deploy_key.pem> ubuntu@ec2-3-87-27-112.compute-1.amazonaws.com 'sh script.sh'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
