...
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Add commands to install any dependencies your project needs

      - name: Deploy to EC2
        run: |
          # Add commands to deploy your application to the EC2 instance
          # Example: scp -i <your-key.pem> -r ./your-app/ ec2-user@<your-ec2-ip>:/path/to/deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
