name: ec2-deploy
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        run: |
              echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
              chmod 400 deploy_key.pem
              ssh -i "deploy_key.pem" ubuntu@ec2-3-80-251-172.compute-1.amazonaws.com 'date >> date.txt'
